# Generated by Django 3.2.5 on 2021-08-16 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dope', '0009_auto_20210808_1624'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creatAt', models.DateTimeField(auto_now_add=True)),
                ('lastModification', models.DateTimeField(auto_now_add=True)),
                ('expireAt', models.DateField()),
                ('maxTasks', models.IntegerField()),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='dope.gateway')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
            },
        ),
    ]
