# Generated by Django 3.2.5 on 2021-08-20 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dope', '0013_auto_20210818_1822'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('month', models.IntegerField()),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='dope.gateway')),
            ],
            options={
                'verbose_name': 'Pricing',
                'verbose_name_plural': 'Pricing',
                'ordering': ['gateway'],
                'unique_together': {('month', 'gateway')},
            },
        ),
    ]
