# Generated by Django 3.2.5 on 2021-07-31 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
        ('dope', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='coupon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='payments.coupon'),
        ),
        migrations.AddField(
            model_name='task',
            name='footLockerAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='dope.footlockeraccount'),
        ),
        migrations.AddField(
            model_name='task',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='dope.gateway'),
        ),
        migrations.AddField(
            model_name='task',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='dope.item'),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suffix',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suffixUrls', to='dope.gateway'),
        ),
        migrations.AddField(
            model_name='nikeaccount',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nike_accounts', to='dope.gateway'),
        ),
        migrations.AddField(
            model_name='nikeaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nike_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gateway',
            name='paymentMethods',
            field=models.ManyToManyField(related_name='gateways', to='dope.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='footlockeraccount',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footlocker_accounts', to='dope.gateway'),
        ),
        migrations.AddField(
            model_name='footlockeraccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footlocker_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
