# Generated by Django 3.2.5 on 2021-08-01 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dope', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='active',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('inprogress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='dope.suffix'),
        ),
    ]
