# Generated by Django 3.2.5 on 2021-08-01 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('dope', '0003_auto_20210801_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='supportedAccount',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='infoStr',
            field=models.CharField(blank=True, max_length=1026, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='coupon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='payments.coupon'),
        ),
        migrations.AlterField(
            model_name='task',
            name='footLockerAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='dope.footlockeraccount'),
        ),
    ]
