# Generated by Django 3.2.5 on 2021-08-01 15:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dope', '0004_auto_20210801_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 15, 38, 8, 216228, tzinfo=utc)),
        ),
    ]
