# Generated by Django 3.2.5 on 2021-08-01 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dope', '0006_alter_task_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['date'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
