# Generated by Django 3.2.5 on 2021-08-01 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dope', '0007_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-id'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='state',
        ),
    ]
