# Generated by Django 3.2.5 on 2021-08-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dope', '0009_auto_20210808_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='priceFor1year',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='priceForTask',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
