# Generated by Django 3.2.5 on 2021-08-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dope', '0010_auto_20210817_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='priceFor1month',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='priceFor3month',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='priceFor6month',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
