# Generated by Django 3.2.5 on 2021-08-17 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dope', '0011_auto_20210817_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gateway',
            name='priceFor1month',
        ),
        migrations.RemoveField(
            model_name='gateway',
            name='priceFor1year',
        ),
        migrations.RemoveField(
            model_name='gateway',
            name='priceFor3month',
        ),
        migrations.RemoveField(
            model_name='gateway',
            name='priceFor6month',
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('month', models.IntegerField()),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='dope.gateway')),
            ],
            options={
                'verbose_name': 'Pricing',
                'verbose_name_plural': 'Pricing',
                'ordering': ['price'],
            },
        ),
    ]
