# Generated by Django 3.2.5 on 2021-08-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dope', '0012_auto_20210817_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='maxTaskForAccount',
            field=models.IntegerField(default=10),
        ),
        migrations.DeleteModel(
            name='Pricing',
        ),
    ]
